# Generated by Django 5.2.6 on 2025-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
